version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Build commands go here"
  post_build:
    commands:
      - echo "Any post build actions go here"

artifacts:
  files:
    - '**/*'
