version: 0.2

env:
  # Use 'secrets-manager' to store your Docker Hub credentials securely.
  secrets-manager:
    DOCKERHUB_USERNAME: DockerHubCredentials:username
    DOCKERHUB_PASSWORD: DockerHubCredentials:password

phases:
  pre_build:
    commands:

      - echo "Logging in to Docker Hub..."
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - export FRONTEND_IMAGE="justinding765/frontend:${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - export BACKEND_IMAGE="justinding765/backend:${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo $FRONTEND_IMAGE
      - echo "Building frontend Docker image..."
      - docker build -t $FRONTEND_IMAGE${CODEBUILD_RESOLVED_SOURCE_VERSION} ./frontend
      - echo "Building backend Docker image..."
      - docker build -t $BACKEND_IMAGE${CODEBUILD_RESOLVED_SOURCE_VERSION} ./backend

  build:
    commands:
      - echo "Pushing frontend Docker image to Docker Hub..."
      - docker push $FRONTEND_IMAGE${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Pushing backend Docker image to Docker Hub..."
      - docker push $BACKEND_IMAGE${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "{\"BackendImageVersion\":\"${CODEBUILD_RESOLVED_SOURCE_VERSION}\",\"FrontendImageVersion\":\"${CODEBUILD_RESOLVED_SOURCE_VERSION}\"}" > parameters.json
      - cat parameters.json
  post_build:
    commands:
      - echo "Build and push completed."

artifacts:
  files:
    - Mock_Interviewer_AWS.yml
    - parameters.json


