version: 0.2

env:
  variables:
    FRONTEND_IMAGE: "justinding765/interviewer:frontend"
    BACKEND_IMAGE: "justinding765/interviewer:backend"
  # Use 'secrets-manager' to store your Docker Hub credentials securely.
  secrets-manager:
    DOCKERHUB_USERNAME: DockerHubCredentials:username
    DOCKERHUB_PASSWORD: DockerHubCredentials:password

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - echo "Building frontend Docker image..."
      - docker build -t $FRONTEND_IMAGE ./frontend
      - echo "Building backend Docker image..."
      - docker build -t $BACKEND_IMAGE ./backend

  build:
    commands:
      - echo "Pushing frontend Docker image to Docker Hub..."
      - docker push $FRONTEND_IMAGE
      - echo "Pushing backend Docker image to Docker Hub..."
      - docker push $BACKEND_IMAGE
      - cat Mock_Interviewer_AWS.yml

  post_build:
    commands:
      - echo "Build and push completed."

artifacts:
  files:
    - Mock_Interviewer_AWS.yml
