version: '3.3'
services:
  frontend-service:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-service

  backend-service:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      PORT: "5000"
     


