---
Resources:
  AwsAcmCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties: 
      DomainName: 'justinming765.site' # Your primary domain name
      DomainValidationOptions: 
        - DomainName: 'justinming765.site' # Domain to be validated
          HostedZoneId: 'Z07579781BIYS8393SNCD'
      # Route 53 Hosted Zone ID
      SubjectAlternativeNames: 
        - '*.justinming765.site'
      ValidationMethod: 'DNS'