apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      nodePort: 31534
      port: 8037
      targetPort: 3000
  type: NodePort  # Use NodePort type for local access